### ISSUE TITLE
`switchTo("newlib")` hangs

### ISSUE THREAD

**Issue by jarodmeng** [gmbecker/switchr#6]
I have two switchr libraries set up. My work system behaves a bit differently from a conventional system. It creates a symlink in my library folder and points to a very large file system that has thousands of files.

When I tried to use `switchTo("newlib")` to create a new library, the command hangs. After a bit investigation, I realized that it hangs on the following line in `updateManifest` in `findCtx.R`.

```
fils = list.files(switchrBaseDir(), recursive = TRUE, full.names = TRUE, pattern = "lib_info")
```

Because of `recursive = TRUE`, `list.files` takes forever to go though all the files in the `.switchr` folder due to those symlinks I mentioned.

My question is why `recursive = TRUE` necessary here? Is nested libraries a possibility that requires the recursive search?

**Comment by gmbecker** [comment]
@jarodmeng, thanks for the report. The recursive is there because the structure is

basedir -> librarydir1 -> lib_info (file)
              -> librarydir2 -> lib_info (file) 

etc. 

Is the issue that you have switchrBaseDir set to a directory which also has many non-switch-library directories in it? The assumption baked into the code is that switchrBaseDir would be something along the lines of ~/.switchr or in your case perhaps /hugefilesystem/.switchr and package libraries would live underneath that.

Does that make sense, and is there something preventing you from setting things up this way for your system?

**Comment by jarodmeng** [comment]
I realized the need to have `recursive = TRUE` after a bit reading.

My problem is that my system doesn't use R CMD INSTALL to install R packages. Instead, it has commands that wrap around R CMD INSTALL. The command create symlinks to /hugefilesystem/ as it installs the R packages. `list.files(recursive = TRUE)` would try to follow the symlinks to read those files and just hang.

I forked `switchr` and replaced the `list.files()` call with

```
fils = system(sprintf('find %s -name "lib_info" -exec readlink -f {} \\;', switchrBaseDir()), intern = TRUE)
```

and now it works fine as `find` by default does not follow symlinks.

This is probably too niche a situation to warrant a change, but I'm happy to submit a PR if you think it's necessary.

Thanks!

**Comment by gmbecker** [comment]
I see now. I think it's fixable, as I was really using recursive there for simplicity's sake. 

Unfortunately, your 'find' system call there isn't  going to be portable enough for me to accept AFAIK, but if you were to change it so that it got the list of directories under switchrBaseDir and only looked for the lib_info file non-recursively in each of those via R code I'd definitely accept a PR that didn't change the end behavior.

**Comment by jarodmeng** [comment]
How about something like

```
sapply(list.dirs(switchrBaseDir(), recursive = FALSE), function(x) list.files(x, full.names = TRUE, pattern = "lib_info"), USE.NAMES = FALSE)
```

I've tested it on my machine and it seems to work fine. I will create a PR and link it to this thread.
